accounts/urls.py
from django.urls import path
from .views import StudentSignupView, FacultySignupView, AdminHomeView, StudentHomeView, FacultyHomeView


app_name = "accounts"
 
urlpatterns = [
    path('student-signup/', StudentSignupView.as_view(), name='student-signup'),
    path('faculty-signup/', FacultySignupView.as_view(), name='faculty-signup'),
    path('admin-home/', AdminHomeView.as_view(), name='admin-home'),
    path('student-home/', StudentHomeView.as_view(), name='student-home'),
    path('faculty-home/', FacultyHomeView.as_view(), name='faculty-home'),
]

dms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, include
from accounts.views import LandingPageView, CalendarView, TimetableView, SyllabusView, FacultyView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('student/', include('student.urls', namespace='students')),
    path('faculty/', include('faculty.urls', namespace='faculty')),
    path('classroom/', include('classroom.urls', namespace='classrooms')),
    path('announcement/', include('announcement.urls', namespace='announcements')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password-reset-done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password-reset-complete'),
    path('academic-calendar/', CalendarView.as_view(), name='academic-calendar'),
    path('timetable/', TimetableView.as_view(), name='timetable'),
    path('syllabus/', SyllabusView.as_view(), name='syllabus'),
    path('faculty-list/', FacultyView.as_view(), name='faculty-list'),
]


if settings.DEBUG: 
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

faculty/urls.py
from django.urls import path

from .views import FacultyListView, FacultyCreateView, FacultyDetailView, FacultyUpdateView, FacultyDeleteView


app_name = "faculty"


urlpatterns = [
    path('', FacultyListView.as_view(), name='faculty-list'),
    path('create/', FacultyCreateView.as_view(), name='faculty-create'),
    path('<int:pk>/', FacultyDetailView.as_view(), name='faculty-detail'),
    path('<int:pk>/update/', FacultyUpdateView.as_view(), name='faculty-update'),
    path('<int:pk>/delete/', FacultyDeleteView.as_view(), name='faculty-delete'),
]

student/urls.py
from django.urls import path

from .views import StudentListView, StudentCreateView, StudentDetailView, StudentUpdateView, StudentDeleteView


app_name = "student"


urlpatterns = [
    path('', StudentListView.as_view(), name='student-list'),
    path('create/', StudentCreateView.as_view(), name='student-create'),
    path('<int:pk>/', StudentDetailView.as_view(), name='student-detail'),
    path('<int:pk>/update/', StudentUpdateView.as_view(), name='student-update'),
    path('<int:pk>/delete/', StudentDeleteView.as_view(), name='student-delete'),
]

faculty/models.py
from django.db import models

faculty/forms.py
from django import forms
from accounts.models import Faculty



class FacultyModelForm(forms.ModelForm):
    class Meta:
        model = Faculty
        fields = (
            'user',
            'profile_picture',
            'phone_number',
            'title',
            'designation',
            'educational_qualification',
            'honors_awards',
            'research_interests',
            'publications',
            'other_responsibliites',
        )

faculty/views.py
from django.shortcuts import reverse
from django.views import generic
from accounts.mixins import FacultyAndAdminLoginRequiredMixin

from accounts.models import Faculty
from .forms import FacultyModelForm



class FacultyListView(FacultyAndAdminLoginRequiredMixin, generic.ListView):
    template_name = "faculty/faculty_list.html"
    context_object_name = "faculty"
    
    def get_queryset(self):
        department = self.request.user.userprofile
        return Faculty.objects.filter(department=department)


class FacultyCreateView(FacultyAndAdminLoginRequiredMixin, generic.CreateView):
    template_name = "faculty/faculty_create.html"
    form_class = FacultyModelForm
    
    def get_success_url(self) :
        return reverse("faculty:faculty-list")
    
    def form_valid(self, form):
        faculty = form.save(commit=False)
        faculty.department = self.request.user.userprofile
        faculty.save()
        return super(FacultyCreateView, self).form_valid(form)


class FacultyDetailView(FacultyAndAdminLoginRequiredMixin, generic.DetailView):
    template_name = "faculty/faculty_detail.html"
    context_object_name = "faculty"

    def get_queryset(self):
        department = self.request.user.userprofile
        return Faculty.objects.filter(department=department)


class FacultyUpdateView(FacultyAndAdminLoginRequiredMixin, generic.UpdateView):
    template_name = "faculty/faculty_update.html"
    form_class = FacultyModelForm
    
    def get_success_url(self) :
        return reverse("faculty:faculty-list")
    
    def get_queryset(self):
        department = self.request.user.userprofile
        return Faculty.objects.filter(department=department)


class FacultyDeleteView(FacultyAndAdminLoginRequiredMixin, generic.DeleteView):
    template_name = "faculty/faculty_delete.html"
    
    def get_success_url(self) :
        return reverse("faculty:faculty-list")
    
    def get_queryset(self):
        department = self.request.user.userprofile
        return Faculty.objects.filter(department=department)

faculty/templates/faculty/faculty_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-md mx-auto">
     <div class="py-5 border-b border-gray-200">
     <a class="hover:text-blue-500" href="{% url 'faculty:faculty-list' %}">Go back to faculty</a>
     </div>
     <div class="py-5 border-t border-gray-200">
      <h1 class="mb-5 text-4xl text-gray-800">Register a  new faculty</h1>
      <a class="text-gray-500 hover:text-blue-500" href="{% url 'accounts:faculty-signup' %}"">
           Create an user account first?
      </a>
</div>
   <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
          Submit
      </button>
   </form>
</div>

{% endblock content %}

faculty/templates/faculty/faculty_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

     <div class="max-w-md mx-auto">
          <div class="py-5 border-b border-gray-200">
               <a class="hover:text-blue-500" href="{% url 'faculty:faculty-list' %}">Go back to faculty</a>
          </div>
         <h1 class="text-3xl text-gray-800">Are you sure you want to delete this faculty?</h1>
          <form method="post" class="mt-5">
               {% csrf_token %}
               {{ form|crispy }}
               <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                    Yes
               </button>
          </form>
     </div>

{% endblock content %}

faculty/templates/faculty/faculty_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">FACULTY</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ faculty.user.first_name }} {{ faculty.user.last_name }}</h1>
                <div class="flex mb-4">
                    <a href="{% url 'faculty:faculty-detail' faculty.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Details
                    </a>
                    <a href="{% url 'faculty:faculty-update' faculty.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Edit
                    </a>
                </div>
                <div class="flex border-b border-gray-300 py-2">
                    <span class="text-gray-500">Name</span>
                    <span class="ml-auto text-gray-900">{{ faculty.title }} {{ faculty.user.first_name }} {{ faculty.user.last_name }}</span>
                </div>
                <div class="flex border-b border-gray-300 py-2">
                    <span class="text-gray-500">Phone Number</span>
                    <span class="ml-auto text-gray-900">{{ faculty.phone_number }}</span>
                </div>
                <div class="flex border-b border-gray-300 py-2">
                    <span class="text-gray-500">Designation</span>
                    <span class="ml-auto text-gray-900">{{ faculty.designation }}</span>
                </div>
                <div class="flex border-b border-gray-300 py-2">
                    <span class="text-gray-500">Educational Qualification</span>
                    <span class="ml-auto text-gray-900">{{ faculty.educational_qualification }}</span>
                </div>
                <div class="flex border-b border-gray-300 py-2">
                    <span class="text-gray-500">Honors and Awards</span>
                    <span class="ml-auto text-gray-900">{{ faculty.honors_awards }}</span>
                </div>
                <div class="flex border-b border-gray-300 py-2">
                    <span class="text-gray-500">Research Interests</span>
                    <span class="ml-auto text-gray-900">{{ faculty.research_interests }}</span>
                </div>
                <div class="flex border-b border-gray-300 py-2">
                    <span class="text-gray-500">Publications</span>
                    <span class="ml-auto text-gray-900">{{ faculty.publications }}</span>
                </div>
                <div class="flex border-b border-gray-300 py-2">
                    <span class="text-gray-500">Other Responsibliites</span>
                    <span class="ml-auto text-gray-900">{{ faculty.other_responsibliites }}</span>
                </div>
            </div>
        </div>
    </div>
  </section>

{% endblock content %}

faculty/templates/faculty/faculty_list.html
{% extends "base.html" %}

{% block content %}

<!-- <aside class="w-64" aria-label="Sidebar">
    <div class="overflow-y-auto py-4 px-3 rounded">
       <ul class="space-y-2">
          <li>
             <a href="#" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg hover:bg-gray-100">
                <span class="ml-3">Dashboard</span>
             </a>
          </li>
          <li>
             <a href="#" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg hover:bg-gray-100">
                <span class="flex-1 ml-3 whitespace-nowrap">Faculty</span>
             </a>
          </li>
          <li>
             <a href="{% url 'students:student-list' %}" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg bg-gray-100">
                <span class="flex-1 ml-3 whitespace-nowrap">Students</span>
             </a>
          </li>
          <li>
             <a href="#" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg hover:bg-gray-100">
                <span class="flex-1 ml-3 whitespace-nowrap">Users</span>
             </a>
          </li>
          <li>
             <a href="#" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg hover:bg-gray-100">
                <span class="flex-1 ml-3 whitespace-nowrap">Products</span>
             </a>
          </li>
          <li>
             <a href="#" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg hover:bg-gray-100">
                <span class="flex-1 ml-3 whitespace-nowrap">Sign In</span>
             </a>
          </li>
          <li>
             <a href="#" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg hover:bg-gray-100">
                <span class="flex-1 ml-3 whitespace-nowrap">Sign Up</span>
             </a>
          </li>
       </ul>
    </div>
</aside> -->

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Faculty</h1>
            </div>
            <div>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'faculty:faculty-create' %}">
                    Register a new faculty
                </a>
            </div>
        </div>

        <div class="flex flex-col w-full items-center">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-auto sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                        <table class="min-w-full divide-y divide-gray-200">
                            <thead class="bg-gray-50">
                                <tr>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Name
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Phone Number
                                    </th>
                                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Email
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for faculty in faculty %}
                                    <tr class="bg-white">
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            {{ faculty.title }} {{ faculty.user.first_name }} {{ faculty.user.last_name }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            {{ faculty.phone_number }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                            {{ faculty.user.email }}
                                        </td>
                                        <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                            <a href="{% url 'faculty:faculty-detail' faculty.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                                View
                                            </a>
                                        </td>
                                    </tr>

                                {% empty %}

                                <p>There are currently no faculty</p>

                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

faculty/templates/faculty/faculty_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">FACULTY</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
                    {{ faculty.user.first_name }} {{ faculty.user.last_name }}
                </h1>
                <div class="flex mb-4">
                    <a href="{% url 'faculty:faculty-detail' faculty.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Details
                    </a>
                    <a href="{% url 'faculty:faculty-update' faculty.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                        Edit
                    </a>
                </div>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
                        Update
                    </button>
                </form>
                <div class="mt-5 py-5  border-t border-gray-200">
                    <a href="{% url 'faculty:faculty-delete' faculty.pk %}" class="w-1/4 mt-3 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                        Delete
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}