classroom/urls.py
from django.urls import path

from .views import ClassroomListView, ClassroomCreateView, ClassroomDetailView, ClassroomUpdateView, ClassroomDeleteView


app_name = "classrooms"


urlpatterns = [
    path('', ClassroomListView.as_view(), name='classroom-list'),
    path('create/', ClassroomCreateView.as_view(), name='classroom-create'),
    path('<int:pk>/', ClassroomDetailView.as_view(), name='classroom-detail'),
    path('<int:pk>/update/', ClassroomUpdateView.as_view(), name='classroom-update'),
    path('<int:pk>/delete/', ClassroomDeleteView.as_view(), name='classroom-delete'),
    
]

dms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, include
from accounts.views import LandingPageView, CalendarView, TimetableView, SyllabusView, FacultyView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('student/', include('student.urls', namespace='students')),
    path('faculty/', include('faculty.urls', namespace='faculty')),
    path('classroom/', include('classroom.urls', namespace='classrooms')),
    path('announcement/', include('announcement.urls', namespace='announcements')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password-reset-done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password-reset-complete'),
    path('academic-calendar/', CalendarView.as_view(), name='academic-calendar'),
    path('timetable/', TimetableView.as_view(), name='timetable'),
    path('syllabus/', SyllabusView.as_view(), name='syllabus'),
    path('faculty-list/', FacultyView.as_view(), name='faculty-list'),
]


if settings.DEBUG: 
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

student/urls.py
from django.urls import path

from .views import StudentListView, StudentCreateView, StudentDetailView, StudentUpdateView, StudentDeleteView


app_name = "student"


urlpatterns = [
    path('', StudentListView.as_view(), name='student-list'),
    path('create/', StudentCreateView.as_view(), name='student-create'),
    path('<int:pk>/', StudentDetailView.as_view(), name='student-detail'),
    path('<int:pk>/update/', StudentUpdateView.as_view(), name='student-update'),
    path('<int:pk>/delete/', StudentDeleteView.as_view(), name='student-delete'),
]

classroom/models.py
from django.db import models

from accounts.models import User, UserProfile
from course.models import Subject



class Classroom(models.Model):
    teacher = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    code = models.CharField("Class code", max_length=50, unique=True)
    name = models.CharField("Class name", max_length=50)
    subject = models.ForeignKey(Subject, null=True, blank=True, on_delete=models.SET_NULL)
    people = models.ManyToManyField(User, related_name='people', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

student/models.py
from django.db import models

# Create your models here.

classroom/forms.py
from django import forms
from .models import Classroom



class ClassroomModelForm(forms.ModelForm):
    class Meta:
        model = Classroom
        fields = (
            'code',
            'name',
            'subject',
        )

student/forms.py
from django import forms
from accounts.models import Student



class StudentModelForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = (
            'user',
            'gender',
            'date_of_birth',
            'phone_number',
            'course',
            'semester',
            'current_year',
        )

classroom/views.py
from django.shortcuts import reverse
from django.views import generic
from accounts.mixins import FacultyAndLoginRequiredMixin

from .models import Classroom
from .forms import ClassroomModelForm


class ClassroomListView(FacultyAndLoginRequiredMixin, generic.ListView):
    template_name = "classrooms/classroom_list.html"
    context_object_name = "classrooms"
    

    def get_queryset(self):
        user = self.request.user
        # initial queryset of classrooms for particular teacher
        if user.is_faculty:
            queryset = Classroom.objects.filter(teacher=user.userprofile)
        else:
            queryset = Classroom.objects.filter(teacher=user.faculty.department)
            # filter for the student that  is logged in
            queryset = queryset.filter(student__user=user)
        return queryset
   
    # def get_queryset(self):
    #     teacher = self.request.user.userprofile
    #     return Classroom.objects.filter(teacher=teacher)


class ClassroomCreateView(FacultyAndLoginRequiredMixin, generic.CreateView):
    template_name = "classroom/classroom_create.html"
    form_class = ClassroomModelForm
    
    def get_success_url(self) :
        return reverse("classroom:classroom-list")
    
    def form_valid(self, form):
        classrooms = form.save(commit=False)
        classrooms.teacher = self.request.user.userprofile
        classrooms.save()
        
        return super(ClassroomCreateView, self).form_valid(form)


class ClassroomDetailView(FacultyAndLoginRequiredMixin, generic.DetailView):
    template_name = "classroom/classroom_detail.html"
    context_object_name = "classroom"

    def get_queryset(self):
        user = self.request.user
        # initial queryset of classrooms for particular teacher
        if user.is_faculty:
            queryset = Classroom.objects.filter(teacher=user.userprofile)
        else:
            queryset = Classroom.objects.filter(teacher=user.student.classrooms.people)
            # filter for the student that  is logged in
            queryset = queryset.filter(student__user=user)
        return queryset

    # def get_queryset(self):
    #     teacher = self.request.user.userprofile
    #     return Classroom.objects.filter(teacher=teacher)


class ClassroomUpdateView(FacultyAndLoginRequiredMixin, generic.UpdateView):
    template_name = "classroom/classroom_update.html"
    form_class = ClassroomModelForm
    
    def get_success_url(self) :
        return reverse("classrooms:classroom-list")
    
    # def get_queryset(self):
    #     user = self.request.user
    #     return Classroom.objects.filter(teacher=user.userprofile)

    def get_queryset(self):
        teacher = self.request.user.userprofile
        return Classroom.objects.filter(teacher=teacher)


class ClassroomDeleteView(FacultyAndLoginRequiredMixin, generic.DeleteView):
    template_name = "classroom/classroom_delete.html"

    def get_success_url(self) :
        return reverse("classroom:classroom-list")

    # def get_queryset(self):
    #     user = self.request.user
    #     return Classroom.objects.filter(teacher=user.userprofile)
    
    def get_queryset(self):
        teacher = self.request.user.userprofile
        return Classroom.objects.filter(teacher=teacher)

student/views.py
from django.core.mail import send_mail
from django.shortcuts import reverse
from django.views import generic
from accounts.mixins import StudentAndAdminLoginRequiredMixin

from accounts.models import Student
from .forms import StudentModelForm


class StudentListView(StudentAndAdminLoginRequiredMixin, generic.ListView):
    template_name = "student/student_list.html"
    context_object_name = "students"
    
    def get_queryset(self):
        department = self.request.user.userprofile
        return Student.objects.filter(department=department)


class StudentCreateView(StudentAndAdminLoginRequiredMixin, generic.CreateView):
    template_name = "student/student_create.html"
    form_class = StudentModelForm
    
    def get_success_url(self) :
        return reverse("student:student-list")
    
    def form_valid(self, form):
        student = form.save(commit=False)
        student.department = self.request.user.userprofile
        student.save()
        send_mail(
            subject="Your student account has been created at DBATU (IT)",
            message="Please change your password and login to the portal by clicking on this link..",
            from_email="it@dbatu.ac.in",
            recipient_list=["student@gmail.com"]
        )
        return super(StudentCreateView, self).form_valid(form)


class StudentDetailView(StudentAndAdminLoginRequiredMixin, generic.DetailView):
    template_name = "student/student_detail.html"
    context_object_name = "student"

    def get_queryset(self):
        department = self.request.user.userprofile
        return Student.objects.filter(department=department)


class StudentUpdateView(StudentAndAdminLoginRequiredMixin, generic.UpdateView):
    template_name = "student/student_update.html"
    form_class = StudentModelForm
    
    def get_success_url(self) :
        return reverse("student:student-list")
    
    def get_queryset(self):
        department = self.request.user.userprofile
        return Student.objects.filter(department=department)


class StudentDeleteView(StudentAndAdminLoginRequiredMixin, generic.DeleteView):
    template_name = "student/student_delete.html"
    
    def get_success_url(self) :
        return reverse("student:student-list")
    
    def get_queryset(self):
        department = self.request.user.userprofile
        return Student.objects.filter(department=department)

classrooms/templates/classrooms/student/classroom_create.html
{% extends "base.html" %}

{% block content %}

    <a href="{% url 'classrooms:classroom-list' %}">Go back to home</a>
    <hr>
    <h1>Create a new classroom</h1>
   <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
   </form>

{% endblock content %}

classrooms/templates/classrooms/student/classroom_delete.html
{% extends "base.html" %}

{% block content %}

    <a href="{% url 'classrooms:classroom-list' %}">Go back to home</a>
    <hr>
    <h1>Are you sure you want to delete this classroom?</h1>
   <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
   </form>

{% endblock content %}

classrooms/templates/classrooms/student/classroom_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">CLASSROOM</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ classroom.name }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'classrooms:classroom-detail' classroom.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Stream</a>
                <!-- <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Classwork</a> -->
                <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">People</a>
                <!-- <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Grades</a> -->
                <a href="{% url 'users:classroom-update' classroom.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Customize
                </a>
            </div>
            <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
            </div>
    </div>
    </div>
  </section>

{% endblock content %}

classrooms/templates/classrooms/student/classroom_list.html
{% extends "base.html" %}

{% block content %}

    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
            <div class="w-full mb-6 py-6 flex justify-between item-center border-b border-gray-200">
                <div>
                    <h1 class="text-4xl text-gray800">Classrooms</h1>
                </div>
                <div>
                    <a class="text-gray-500 hover:text-blue-500" href="{% url 'classrooms:classroom-create' %}">Create a new classroom</a>
                </div>
            </div>
        <div class="flex flex-wrap -m-4">
            {% for classroom in classrooms %}
                <div class="p-4 lg:w-1/2 md:w-full">
                <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                    <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                        <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                    </svg>
                    </div>
                    <div class="flex-grow">
                    <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                        {{ classroom.name }}
                    </h2>
                    <p class="leading-relaxed text-base">
                        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Corporis aut illo dignissimos sunt totam, incidunt laboriosam inventore quidem voluptates velit laudantium provident, tempora quam autem quae quo numquam cumque sint.
                    </p>
                    <a href="{% url 'classrooms:classroom-detail' classroom.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">View classroom
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                        </svg>
                    </a>
                    </div>
                </div>
                </div>
            {% endfor %}
        </div>
        </div>
    </section>

{% endblock content %}

classrooms/templates/classrooms/student/classroom_update.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
          <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                    <h2 class="text-sm title-font text-gray-500 tracking-widest">CLASSROOM</h2>
                    <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ classroom.name }}</h1>
                    <div class="flex mb-4">
                    <a href="{% url 'users:classroom-detail' classroom.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Stream</a>
                    <!-- <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Classwork</a> -->
                    <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">People</a>
                    <!-- <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Grades</a> -->
                    <a href="{% url 'classrooms:classroom-update' classroom.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                         Customize
                    </a>
                    </div>
                         <form method="post">
                              {% csrf_token %}
                              {{ form.as_p }}
                              <button type="submit">Submit</button>
                         </form>
                         <a href="{% url 'classrooms:classroom-delete' classroom.pk %}" class="w-1/4 mt-3 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                              Delete
                         </a>
          </div>
      </div>
    </div>
  </section>

{% endblock content %}